### ISSUE TITLE
libjpeg-turbo and jpeg clobbering each other

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/pillow-feedstock#133]
From discussion in #126:
> > > @ocefpaf: We need an ecosystem wide migration to drop jpeg in lieu of libjeg-turbo to merge https://github.com/conda-forge/pillow-feedstock/pull/128. While that is, IMO the best path we cannot merge that right now until we start the migration.
> >
> > @h-vetinari: You do realise that you merged the libjpeg-turbo version in #132?
> 
> @ocefpaf: Yep. Kind of wanted to give it a go after thinking about it. I believe we can start updating the feedstocks without a migration.

From #132:
>   This does not seem to be working as expected:
```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/win-64::jpeg-9e-h8ffe710_2, conda-forge/win-64::libjpeg-turbo-2.1.4-hcfcfb64_0
  path: 'library/include/jpeglib.h'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/win-64::jpeg-9e-h8ffe710_2, conda-forge/win-64::libjpeg-turbo-2.1.4-hcfcfb64_0
  path: 'library/lib/jpeg.lib'
```

> (Seen in https://github.com/conda-forge/gymnasium-feedstock/pull/9)

_Originally posted by @h-vetinari in https://github.com/conda-forge/pillow-feedstock/issues/132#issuecomment-1374966203_

**Comment by hmaarrfk** [comment]
yeah, we have a libjpeg turbo mapped out, just nobody had time to go through it. can we revert the use of libjpeg turbo here?

**Comment by hmaarrfk** [comment]
xref; https://github.com/conda-forge/conda-forge.github.io/issues/673

**Comment by h-vetinari** [comment]
@ocefpaf decided to merge #132 after thinking about it (see thread starting [here](https://github.com/conda-forge/pillow-feedstock/pull/126#issuecomment-1368790048). I don't mind what we do either way.

**Comment by ocefpaf** [comment]
We probably need to full migration. Hopefully this will be the trigger for us to discuss this. We should phase out the jpeg library and move to the better maintained libjpeg-turbo.

**Comment by jakirkham** [comment]
Can we do something like `blas`?

Recall this was complicated before because of version compatibility/feature support, but am hoping that gap has closed over time to make this easier

**Comment by hmaarrfk** [comment]
Can we discuss in https://github.com/conda-forge/conda-forge.github.io/issues/673#issuecomment-639115091

**Comment by hmaarrfk** [comment]
as a Pillow specific question, can today's pillow be built with standard jpeg (i.e. not libjpeg-turbo)

**Comment by hmaarrfk** [comment]
I somewhat see this move to using jpeg turbo has counter to the open discussion we had referenced above.

I think it would be good if we reverted the merge with turbo, see https://github.com/conda-forge/pillow-feedstock/pull/134, and made pillow depend on `jpeg` instead until the conversation at https://github.com/conda-forge/conda-forge.github.io/issues/673 is resolved.
