### ISSUE TITLE
Should libtiff be pinned?

### ISSUE THREAD

**Issue by bernt-matthias** [conda-forge/pillow-feedstock#135]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

For a quite recent version of pillow (8.3.1 .. and apparently I cant get a newer one at the moment) I get

```
>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: libtiff.so.5: cannot open shared object file: No such file or directory
```

`libtiff` was installed in 4.5 which comes with `.so.6`, 4.4 seems to still have `.so.5`

so I was wondering if libtiff should be pinned, or if this would not help?

conda forge seems to do this at the moment: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/fe45b7e7c7350a2269468707971492e0495246bc/recipe/conda_build_config.yaml#L533 but I do not understand this mechanism yet.

### Installed packages

```shell
see https://dev.azure.com/bioconda/25074ded-3133-43ca-af80-895ab87b53cb/_apis/build/builds/28644/logs/20
```

### Environment info

```shell
see https://dev.azure.com/bioconda/25074ded-3133-43ca-af80-895ab87b53cb/_apis/build/builds/28644/logs/20
```

**Comment by bgruening** [comment]
It should be pinned. But this works with global pins, very much like in bioconda. You can see the global pins in every repo, like here: https://github.com/conda-forge/pillow-feedstock/blob/main/.ci_support/linux_64_python3.11.____cpython.yaml#L17

**Comment by bernt-matthias** [comment]
Thanks for the info, so I should change it in this file?

**Comment by bgruening** [comment]
No those are global pins, it should not be changed. All packages should be build against that version. Otherwise all packages needs to be rebuild against the new version.
The question is which package was not build against that version?

**Comment by bernt-matthias** [comment]
Seems that in version 8.3.1 the pin for libtiff was to loose https://github.com/conda-forge/pillow-feedstock/blob/a2215ab6a72c31964302d0c8e135d51d28ad5c67/.ci_support/linux_64_python3.6.____cpython.yaml#L18

So I guess this is fine now .. and I'm stuck with manually pinning my package.

**Comment by h-vetinari** [comment]
Conda-forge hasn't been building python 3.6 for a long time now, and same for 3.7 since almost half a year. I recommend you upgrade ASAP. :)
