### ISSUE TITLE
Missing dependency on xorg-libxau

### ISSUE THREAD

**Issue by AaronOpfer** [conda-forge/pillow-feedstock#140]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

My users experience issues using pillow from containers based on RHEL7 with little-to-no RPMs installed.

They used pillow 9.5.0-py310h582fbeb_1

Importing `PIL.Image` fails:

```
ImportError: libXau.so.6: cannot open shared object file: No such file or directory
```
There appears to be `xorg-libxau 1.0.11` in the "root-packages" metadata for this Pillow build. I suspect Pillow detected the presence of this library and configured it / linked against it, however it is not stated as a Pillow build dependency.

Directing users to install this package causes their import to succeed.

### Installed packages

```shell
I cannot provide this list because it contains sensitive information.
```

### Environment info

```shell
I cannot provide this list because it contains sensitive information.
```

**Comment by ocefpaf** [comment]
> My users experience issues using pillow from containers based on RHEL7 with little-to-no RPMs installed.

We cannot help you much without the debug info. Note that conda does expect xorg stuff to be installed in the users systems. While we do provide some limited xorg functionality, see https://anaconda.org/conda-forge/xorg-libxau/, we don't advertise that b/c it is not guaranteed to work.

Closing this but feel free to open a new one with the debug info so we may help you.

**Comment by AaronOpfer** [comment]
Thanks for your response. I was attempting to create some clean debugging info by replacing sensitive configurations with public setups, and in the process accidentally proved that an ordinary configuration using public channels does not provoke this behavior, and as such I turn my attention to my internal tools.

**Comment by nulano** [comment]
Pillow does not have a direct dependency on libXau.
libXau is a dependency of libxcb, an optional dependency of Pillow.
