### ISSUE TITLE
pillow 4.1.0 and fails in AppVeyor for Py36

### ISSUE THREAD

**Issue by stadelmanma** [conda-forge/pillow-feedstock#30]
I don't have regular access to a Windows machine to do a more thorough debugging but my last successful build was 13 days ago which matches up with the 4.1.0 merge. Although I have a several day gap between that and my first failing build where I didn't push any commits). Nothing regarding that portion of my code changed which could explain the odd behavior. The only constraint on my pillow requirements is `>=3.4.0`.

**Last successful build for Py36**
https://ci.appveyor.com/project/stadelmanma/netl-ap-map-flow/build/0.0.51/job/7j3l5flktdseuyk7
conda installed packages
```
The following NEW packages will be INSTALLED:
    freetype:  2.7-vc14_1         conda-forge [vc14]
    jpeg:      9b-vc14_0          conda-forge [vc14]
    libpng:    1.6.28-vc14_0      conda-forge [vc14]
    libtiff:   4.0.6-vc14_7       conda-forge [vc14]
    mkl:       2017.0.1-0         defaults   
    numpy:     1.12.1-py36_0      defaults   
    olefile:   0.44-py36_0        conda-forge
    pillow:    4.0.0-py36_2       conda-forge
    pint:      0.7.2-py36_2       conda-forge
    pyyaml:    3.12-py36_1        conda-forge
    scipy:     0.19.0-np112py36_0 defaults   
    vc:        14-0               conda-forge
    yaml:      0.1.6-vc14_0       conda-forge [vc14]
    zlib:      1.2.11-vc14_0      conda-forge [vc14]
```
What setup.py registers:
```
Installed c:\projects\netl-ap-map-flow
Processing dependencies for ApertureMapModelTools==0.0.1
Searching for PyYAML==3.12
Best match: PyYAML 3.12
Adding PyYAML 3.12 to easy-install.pth file
Using c:\miniconda36-x64\lib\site-packages
Searching for Pillow==4.4.0
Best match: Pillow 4.4.0
Adding Pillow 4.4.0 to easy-install.pth file
Using c:\miniconda36-x64\lib\site-packages
Searching for scipy==0.19.0
Best match: scipy 0.19.0
Adding scipy 0.19.0 to easy-install.pth file
Using c:\miniconda36-x64\lib\site-packages
Searching for numpy==1.12.1
Best match: numpy 1.12.1
Adding numpy 1.12.1 to easy-install.pth file
Using c:\miniconda36-x64\lib\site-packages
Searching for olefile==0.44
Best match: olefile 0.44
Adding olefile 0.44 to easy-install.pth file

```

**First failing build**
https://ci.appveyor.com/project/stadelmanma/netl-ap-map-flow/build/0.0.52/job/5g3t6td00x5s8c1l
Conda installed packages
```
    freetype:  2.7-vc14_1         conda-forge [vc14]
    jpeg:      9b-vc14_0          conda-forge [vc14]
    libpng:    1.6.28-vc14_0      conda-forge [vc14]
    libtiff:   4.0.6-vc14_7       conda-forge [vc14]
    mkl:       2017.0.1-0         defaults   
    numpy:     1.12.1-py36_0      defaults   
    olefile:   0.44-py36_0        conda-forge
    pillow:    4.1.0-py36_0       conda-forge
    pint:      0.7.2-py36_2       conda-forge
    pyyaml:    3.12-py36_1        conda-forge
    scipy:     0.19.0-np112py36_0 defaults   
    vc:        14-0               conda-forge
    yaml:      0.1.6-vc14_0       conda-forge [vc14]
    zlib:      1.2.11-vc14_0      conda-forge [vc14]
```

What pip registers after setup.py
```
Processing dependencies for ApertureMapModelTools==0.0.1
Searching for PyYAML==3.12
Best match: PyYAML 3.12
Adding PyYAML 3.12 to easy-install.pth file
Using c:\miniconda36-x64\lib\site-packages
Searching for Pillow==4.1.0
Best match: Pillow 4.1.0
Adding Pillow 4.1.0 to easy-install.pth file
Using c:\miniconda36-x64\lib\site-packages
Searching for scipy==0.19.0
Best match: scipy 0.19.0
Adding scipy 0.19.0 to easy-install.pth file
Using c:\miniconda36-x64\lib\site-packages
Searching for numpy==1.12.1
Best match: numpy 1.12.1
Adding numpy 1.12.1 to easy-install.pth file
Using c:\miniconda36-x64\lib\site-packages
Searching for olefile==0.44
Best match: olefile 0.44
Adding olefile 0.44 to easy-install.pth file
```

**Error Message**
```
Using c:\miniconda36-x64\lib\site-packages
Finished processing dependencies for ApertureMapModelTools==0.0.1
python .\bin\build_model -m mingw32-make all STATIC_FLAG=-static
Traceback (most recent call last):
  File ".\bin\build_model", line 8, in <module>
    import ApertureMapModelTools as amt
  File "c:\projects\netl-ap-map-flow\ApertureMapModelTools\__init__.py", line 19, in <module>
    from .__core__ import DataField, FractureImageStack
  File "c:\projects\netl-ap-map-flow\ApertureMapModelTools\__core__.py", line 18, in <module>
    from PIL import Image
  File "C:\Miniconda36-x64\lib\site-packages\PIL\Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified procedure could not be found.
Command exited with code 1
```

**Comment by patricksnape** [comment]
I can't replicate this on my Windows 64 VM - could this have something to do with your mingw environment having binaries such as jpeg that get loaded before the pillow jpeg causing linking issues?

**Comment by stadelmanma** [comment]
@patricksnape Pillow 4.0.0 works in both and Python 3.5 doesn't share the same issue using 4.1.0. Additionally, I tested just copying the files I need locally instead of modifying the %PATH% variable to include the MinGW bin and I got the same error in Py36 as before.
https://ci.appveyor.com/project/stadelmanma/netl-ap-map-flow/build/0.0.70/job/ut4v2xxrwjp2chdg

I call conda activate.bat so Anaconda should have preference over everything else on the path. Just for kicks I tried calling it during both install and build with the same result.

My environment is pretty vanilla minus adding MinGW and Anaconda to the path so I wouldn't expect any odd conflicts either.

**Comment by patricksnape** [comment]
Yes, I made a fresh environment on my machine, installed all the exact deps you specify I don't get an import error - so I'm a bit stumped.

**Comment by Chilipp** [comment]
Hi! I can confirm the bug and ran across the same issue. Here is, how you can reproduce it:

1. Download the [latest miniconda installer for windows](https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe)
2. install miniconda
3. install ``pillow`` via ``conda install -c conda-forge pillow -y``
4. running ``python -c "import PIL.Image"`` gives
   ```
   Traceback (most recent call last):
   File "<string>", line 1, in <module>
   File "C:\Users\PSommer\Miniconda3\lib\site-packages\PIL\Image.py", line 56, in <module>
     from . import _imaging as core
   ImportError: DLL load failed: The specified procedure could not be found.
   ```

**Comment by Chilipp** [comment]
Okay, for my case the solution was to use python 3.6.1 from conda-forge (instead of python 3.6.0 from the above installer). Therefore I recommend to try

```bash
conda update -c conda-forge python
```

which should solve the problem

**Comment by stadelmanma** [comment]
That seems to have fixed it on my end as well. Surprising that is the fix but good to know.

**Comment by jakirkham** [comment]
It is interesting that you mention the python install made the difference. Does the same problem occur between python 3.6.0 and 3.6.1 from conda-forge? If so, I wonder if it is related to a recent [ABI break]( https://bugs.python.org/issue29943 ) that occurred between python 3.6.0 and 3.6.1.

**Comment by stadelmanma** [comment]
@jakirkham I confirmed that the same error occurs with Python 3.6.0 downloaded from conda-forge using a Windows VM.

**Comment by jakirkham** [comment]
Yep, looks like that is the issue. ( https://github.com/python-pillow/Pillow/issues/2479 ) Upstream has included a patch, which should help things. ( https://github.com/python-pillow/Pillow/pull/2493 ) FWIW [lots of other people]( http://stackoverflow.com/questions/43264773/pil-dll-load-failed-specified-procedure-could-not-be-found ) have this issue as well. So hoping the core Python team comes up with a fix instead of having every library add this hack.
