### ISSUE TITLE
windows 5.2.0, 5.3.0 missing

### ISSUE THREAD

**Issue by ReimarBauer** [conda-forge/pillow-feedstock#53]
Hi there

it looks like the windows 32 bit build CI has not pushed the new version since 5.1.0 

https://anaconda.org/conda-forge/pillow

Please can you have a look.

Thx.
Reimar

**Comment by ocefpaf** [comment]
> it looks like the windows 32 bit build CI has not pushed the new version since 5.1.0

`conda-forge` stopped building Windows-32 last year :grimacing: 

We just don't have the CI and manpower to support it.
