### ISSUE TITLE
Require the LittleCMS library?

### ISSUE THREAD

**Issue by WarrenWeckesser** [conda-forge/pillow-feedstock#58]
It appears that the conda `pillow` package does not specify its dependence on the [LittleCMS](http://www.littlecms.com/) library, so attempting to use `PIL.ImageCMS` results in an error.  Is it possible to get this dependency included with pillow?  `recipe/build.sh` has the commented line `# export LCMS_ROOT=None`, so apparently some thought was put into this in the past.

**Comment by ocefpaf** [comment]
Sure. Do you want to send a PR to add that dependency?

**Comment by WarrenWeckesser** [comment]
I don't think I'll have time in the near future to figure that out.  If there are no conda gurus who can do it, then perhaps you can keep this issue open as a "wish list" item.

**Comment by kmilos** [comment]
Would be great to include it for all platforms at that: https://github.com/conda-forge/lcms2-feedstock/pull/3
