### ISSUE TITLE
OSError: -2 when decoding compressed TIFF files

### ISSUE THREAD

**Issue by kmilos** [conda-forge/pillow-feedstock#68]
See https://github.com/python-pillow/Pillow/issues/4237
 
Seems to be happening only w/ the conda package, the statically linked wheel from PyPI works.

**Comment by ocefpaf** [comment]
Works for me on Linux. Can you please provide the required debug information in the issue template? Without it we cannot debug your particular case.

Closing this so you can open a new one with the required info. Thanks!
