### ISSUE TITLE
Python 3.4 32-bit failing on Windows/AppVeyor

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pillow-feedstock#9]
For some reason this cannot find `zlib` on Python 3.4 32-bit on Windows. All other Windows builds work fine. This will cause/is causing a failure `master`.

**Comment by patricksnape** [comment]
I will look at this tomorrow, but maybe we can just patch the `setup.py` and set the [ZLIB_ROOT](https://github.com/python-pillow/Pillow/blob/master/setup.py#L117)?

**Comment by patricksnape** [comment]
Also, setting the `DEBUG` flag to `True` [here](https://github.com/python-pillow/Pillow/blob/master/setup.py#L45) might go a long way to debugging this.

**Comment by ocefpaf** [comment]
Master seems to be failing in all archs now.

```
LINK : fatal error LNK1104: cannot open file 'python27_d.lib'
```

Is that b/c you set the debug mode?

**Comment by jakirkham** [comment]
Nope. I removed the debug mode stuff.

**Comment by ocefpaf** [comment]
BTW I am having trouble with `zlib` on libnetcdf too. See https://github.com/conda-forge/libnetcdf-feedstock/pull/1

**Comment by jakirkham** [comment]
> I removed the debug mode stuff.

I guess not. Well, the rest of it is removed now.

**Comment by jakirkham** [comment]
So, interesting fact, it was `zlib`. Now the issue is `jpeg`. See the [log]( https://ci.appveyor.com/project/conda-forge/pillow-feedstock/build/1.0.27/job/qm4tr0g2pad9mtdh#L452 ).

**Comment by jakirkham** [comment]
Should add that it was using `zlib` from `defaults`, but now it is from `conda-forge`.

**Comment by ocefpaf** [comment]
I bumped our `zlib` build number in an attempt to fix `libnetcdf` :grimacing:

**Comment by jakirkham** [comment]
Basically, this is back to the original failure Python 3.4 32-bit Windows failur. So, if you want to take a look, @patricksnape, feel free.
